policy_node:
  ros__parameters:
    model_type: "diffusion"
    checkpoint_path: "/ros/visuomotor_core/outputs/train_502_dataV5/" #si 400_dataV4 500  300_dataV3  20      no 100, 50
    inference_hz: 20.0
    num_inference_steps: 10
    n_action_steps: 8
    camera_topic: "/rgb"
    home_x: 0.25
    home_y: 0.0
    home_z: 0.40
    home_roll: 3.14159
    home_pitch: 0.0
    home_yaw: 0.0
