"**":
  ros__parameters:
    # Ruta del dataset en formato zarr
    dataset_path: "demonstrations.zarr"
    # Frecuencia de recolección de los datos (Hz)
    sampling_rate_hz: 20.0
    
    # Activar PID en modo automático para generar comandos hacia el objeto (True en Isaac Sim)
    enable_auto_pid: true
    # Marco de coordenadas del objeto a seguir (proporcionado por Isaac Sim)
    object_frame: "pick_target"
    # Marco de coordenadas del efector final del brazo
    ee_frame: "gripper_base_link"
    
    # Offset Z para compensar la longitud del gripper y evitar chocar contra el suelo
    tcp_offset_z: 0.079
    
    # Ganancias y límites del controlador PID Cartesiano
    kp: 1.0
    ki: 0.0
    kd: 0.05
    max_speed_m_s: 0.07       # Límite de velocidad máxima permitida (metros por segundo)
    
    # Parámetros de la secuencia Pick up and Approximate
    init_x: 0.25              # Posición inicial oficial en X (metros)
    init_y: 0.0               # Posición inicial oficial en Y (metros)
    init_z_height: 0.40       # Altura inicial para enfocar con la cámara (metros)
    wait_time_s: 5.5          # Segundos de espera en la altura inicial
    hover_z_offset: 0.05      # Altura extra sobre el objeto durante ALIGN (metros)
    grasp_wait_time_s: 2.0    # Segundos esperando que el gripper cierre físicamente
    settle_time_s: 2.5        # Segundos de espera inmóvil en el objetivo antes de cerrar
    approach_timeout_s: 60.0  # Timeout máximo por fase (segundos)
    lift_z_offset: 0.20       # Altura a la que sube el objeto después de agarrarlo (metros)

    # Parámetros avanzados de Control y Tolerancias
    control_rate_hz: 100.0    # Frecuencia del bucle de control interno (Hz)
    goal_tolerance_m: 0.01    # Distancia al objetivo para considerar que se llegó (metros)
    gripper_open_pos: 0.0    # Posición del gripper abierto
    gripper_closed_pos: -0.01   # Posición del gripper cerrado
