sim_collector_node:
  ros__parameters:
    # Ruta del dataset en formato zarr
    dataset_path: "demonstrations.zarr"
    # Frecuencia de recolección de los datos (Hz)
    sampling_rate_hz: 20.0
    
    # Activar PID en modo automático para generar comandos hacia el objeto (True en Isaac Sim)
    enable_auto_pid: true
    # Marco de coordenadas del objeto a seguir (proporcionado por Isaac Sim)
    object_frame: "pick_target"
    # Marco de coordenadas del efector final del brazo
    ee_frame: "gripper_base_link"
    
    # Offset Z para compensar la longitud del gripper y evitar chocar contra el suelo
    tcp_offset_z: 0.08
    
    # Ganancias del controlador PID Cartesiano
    kp: 1.0
    ki: 0.0
    kd: 0.05
    
    # Parámetros de la secuencia Pick up and Approximate
    init_x: 0.25              # Posición inicial oficial en X (metros)
    init_y: 0.0               # Posición inicial oficial en Y (metros)
    init_z_height: 0.40       # Altura inicial para enfocar con la cámara (metros)
    wait_time_s: 5.0          # Segundos de espera en la altura inicial
    grasp_wait_time_s: 3.0    # Segundos de espera para que cierre el gripper
    lift_z_offset: 0.35       # Altura a la que sube el objeto después de agarrarlo (metros)
